spring.application.name=game-hub

# Conexão PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/gamehub_db
spring.datasource.username=postgres 
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração Hibernate / JPA

spring.jpa.hibernate.ddl-auto=update # Atualiza a estrutura da tabela no banco automaticamente
spring.jpa.show-sql=true # Depuração
spring.jpa.properties.hibernate.format_sql=true # Depuração
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
